CREATE TABLE USER_INFO (USER_ID serial PRIMARY KEY,
USERNAME VARCHAR(50) UNIQUE NOT NULL,
AVATAR VARCHAR(255) NOT NULL,
ROLE CHAR(1) NOT NULL DEFAULT '0',
CREATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UPDATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE ACCOUNT (ACCOUNT_ID serial PRIMARY KEY,
USER_ID int NOT NULL,
EMAIL VARCHAR(50) UNIQUE NOT NULL,
HASH VARCHAR(255) NOT NULL,
SALT VARCHAR(50) NOT NULL,
CREATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UPDATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (USER_ID) REFERENCES USER_INFO(USER_ID));


CREATE TABLE AUTHOR (AUTHOR_ID serial PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
SLUG VARCHAR(255) UNIQUE NOT NULL,
CREATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);


CREATE TABLE SOURCE (SOURCE_ID serial PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
SLUG VARCHAR(255) UNIQUE NOT NULL,
URL VARCHAR(255) UNIQUE NOT NULL,
CREATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);


CREATE TABLE GENRE (GENRE_ID serial PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
SLUG VARCHAR(255) UNIQUE NOT NULL,
CREATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);


CREATE TABLE BOOK (BOOK_ID serial PRIMARY KEY,
TITLE VARCHAR(200) NOT NULL,
SLUG VARCHAR(255) UNIQUE NOT NULL,
SUMMARY text, VISIBILITY int NOT NULL DEFAULT 0,
STAR int NOT NULL DEFAULT 0,
STATUS CHAR(1) NOT NULL DEFAULT '0',
AUTHOR_ID int NOT NULL,
SOURCE_ID int NOT NULL,
CREATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UPDATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(AUTHOR_ID),
FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE(SOURCE_ID));


CREATE TABLE BOOK_USER_READING (USER_ID int NOT NULL,
BOOK_ID int NOT NULL,
CREATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UPDATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (USER_ID,
BOOK_ID),
FOREIGN KEY (USER_ID) REFERENCES USER_INFO(USER_ID),
FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID));


CREATE TABLE BOOK_USER_STORE (BOOK_USER_STORE_ID serial PRIMARY KEY,
USER_ID int NOT NULL,
BOOK_ID int NOT NULL,
INDEX int NOT NULL,
STORE_NAME VARCHAR(200) NOT NULL,
CREATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UPDATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (USER_ID) REFERENCES USER_INFO(USER_ID),
FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID));


CREATE TABLE BOOK_GENRE (BOOK_ID int NOT NULL,
GENRE_ID int NOT NULL,
CREATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (GENRE_ID) REFERENCES GENRE(GENRE_ID),
FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID));


CREATE TABLE CHAPTER (CHAPTER_ID serial PRIMARY KEY,
BOOK_ID int NOT NULL,
CHAPTER_NUMBER smallint NOT NULL,
TITLE VARCHAR(200) NOT NULL,
SLUG VARCHAR(255) NOT NULL,
CONTEXT text NOT NULL,
CREATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UPDATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID));



-- delete query
DROP TABLE PUBLIC.USER_INFO;
DROP TABLE PUBLIC.ACCOUNT;
DROP TABLE PUBLIC.BOOK_USER_STORE;
DROP TABLE PUBLIC.BOOK_USER_READING;
DROP TABLE PUBLIC.BOOK_GENRE;
DROP TABLE PUBLIC.CHAPTER;
DROP TABLE PUBLIC.BOOK;
DROP TABLE PUBLIC.SOURCE;
DROP TABLE PUBLIC.GENRE;
DROP TABLE PUBLIC.AUTHOR;
